project:
  type: website

website:
  title: "Lit literature review"
  navbar:
    left:
      - href: sections/GEDI.qmd
        text: GEDI
      - href: sections/forest_fires.qmd
        text: Forest fires
      - href: sections/other_satellites.qmd
        text: Other satellites
      - href: sections/Modelling.qmd
        text: Modelling
      - href: sections/knowledge_gaps.qmd
        text: Knowledge gap
format:
  html:
    css: styles.css
    toc: true
