project:
  type: website

website:
  title: "Lit literature review"
  reader-mode: true
  navbar:
    left:
      - href: sections/first_chapter.qmd
        text: Objective 1
      - href: sections/second_chapter.qmd
        text: Objective 2
      - href: sections/third_chapter.qmd
        text: Objective 3
      - href: test_gedidb.ipynb
        text: Some tests with GEDI data
      - href: sections/presentation.qmd
        text: Slides
      # - href: sections/GEDI.qmd
      #   text: GEDI & Lidar
      # - href: sections/forest_fires.qmd
      #   text: Forest fires
      # - href: sections/other_satellites.qmd
      #   text: Other satellites
      # - href: sections/Modelling.qmd
      #   text: Modelling
