project:
  type: website

website:
  title: "Lit literature review"
  navbar:
    left:
      - href: sections/a_main.qmd
        text: Main
      - href: sections/first_chapter.qmd
        text: Objective 1
      - href: sections/second_chapter.qmd
        text: Objective 2
      - href: sections/third_chapter.qmd
        text: Objective 3
      - href: sections/fourth_chapter.qmd
        text: Objective 4
      # - href: sections/GEDI.qmd
      #   text: GEDI & Lidar
      # - href: sections/forest_fires.qmd
      #   text: Forest fires
      # - href: sections/other_satellites.qmd
      #   text: Other satellites
      # - href: sections/Modelling.qmd
      #   text: Modelling
      # - href: sections/knowledge_gaps.qmd
      #   text: Knowledge gap
format:
  html:
    css: styles.css
    toc: true
