---
from: markdown+emoji
toc: true
toc-depth: 2
jupyter: python3
bibliography: ../references.bib
embed-resources: true
---

# Evaluate the scalability of integrating GEDI and Earth observation data for detecting fire-induced vegetation changes and improving fire emission estimates 

## Main idea

-  Fire emission models can underestimate emissions due to exclusion of small fires and fixed (biome-specific) combustion completeness factors.

:::{layout-ncol="2"}

**Hypothesis:** If a model integrating GEDI and EO data can perform well for a specific domain (region of interest), geographical generalization methods could be used to implement that model in different regions. And this model could be used to improve combustion completeness estimation for fire emission models. 

**Proposed outcome:** A global model for vegetation structure change evaluation caused by fires.

:::

## Literature review

- Location embeddings (SatCLIP)

#### Foundation models (GFZ)

Self-supervised learning + scale make them capable of generalize so well for multiple tasks.