on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  test_env:
    environment: TEST_SECRET
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
        
    - name: Test env vars for python
      env:
        MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }} 
      run: python -c 'import os;print(os.environ['MAPBOX_TOKEN'])'
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install jupyter
      - run: pip install -r requirements.txt

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }} 